version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: